### ISSUE TITLE
android: Unexpected error initializing camera

### ISSUE THREAD

**Issue by inaffect-ag** [appcelerator-archive/ti.barcode#47]
I'm having errors trying to use the barcode scanner v. 3.0.0
I'm using Titanium 6.0.2.GA, node 4.6.2 and targeting Android SDK API: 23

Is this a known issue? anything i could try to make it work?

```[WARN] :   CameraBase: An error occurred while connecting to camera 0: Service not available
[WARN] :   CaptureActivity: Unexpected error initializing camera
[WARN] :   CaptureActivity: java.lang.RuntimeException: Fail to connect to camera service
[WARN] :   CaptureActivity: 	at android.hardware.Camera.<init>(Camera.java:496)
[WARN] :   CaptureActivity: 	at android.hardware.Camera.open(Camera.java:360)
[WARN] :   CaptureActivity: 	at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:166)
[WARN] :   CaptureActivity: 	at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:772)
[WARN] :   CaptureActivity: 	at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:477)
[WARN] :   CaptureActivity: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
[WARN] :   CaptureActivity: 	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:247)
[WARN] :   CaptureActivity: 	at android.view.View.dispatchWindowVisibilityChanged(View.java:10357)
[WARN] :   CaptureActivity: 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
[WARN] :   CaptureActivity: 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
[WARN] :   CaptureActivity: 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
[WARN] :   CaptureActivity: 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
[WARN] :   CaptureActivity: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1544)
[WARN] :   CaptureActivity: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
[WARN] :   CaptureActivity: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
[WARN] :   CaptureActivity: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
[WARN] :   CaptureActivity: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
[WARN] :   CaptureActivity: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
[WARN] :   CaptureActivity: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
[WARN] :   CaptureActivity: 	at android.os.Handler.handleCallback(Handler.java:751)
[WARN] :   CaptureActivity: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN] :   CaptureActivity: 	at android.os.Looper.loop(Looper.java:154)
[WARN] :   CaptureActivity: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[WARN] :   CaptureActivity: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   CaptureActivity: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[WARN] :   CaptureActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[WARN] :   BarcodeModule: (main) [13051,18561] Result for scan was CANCELED
[ERROR] :  WindowManager:
[ERROR] :  WindowManager: android.view.WindowLeaked: Activity com.google.zxing.client.android.CaptureActivity has leaked window DecorView@5dc52a1[] that was originally added here
[ERROR] :  WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
[ERROR] :  WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
[ERROR] :  WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
[ERROR] :  WindowManager: 	at android.app.Dialog.show(Dialog.java:322)
[ERROR] :  WindowManager: 	at android.app.AlertDialog$Builder.show(AlertDialog.java:1112)
[ERROR] :  WindowManager: 	at com.google.zxing.client.android.CaptureActivity.displayFrameworkBugMessageAndExit(CaptureActivity.java:795)
[ERROR] :  WindowManager: 	at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:785)
[ERROR] :  WindowManager: 	at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:477)
[ERROR] :  WindowManager: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
[ERROR] :  WindowManager: 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
[ERROR] :  WindowManager: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
[ERROR] :  WindowManager: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
[ERROR] :  WindowManager: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
[ERROR] :  WindowManager: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
[ERROR] :  WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
[ERROR] :  WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
[ERROR] :  WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
[ERROR] :  WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
[ERROR] :  WindowManager: 	at android.os.Handler.handleCallback(Handler.java:751)
[ERROR] :  WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  WindowManager: 	at android.os.Looper.loop(Looper.java:154)
[ERROR] :  WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[ERROR] :  WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[ERROR] :  WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)```

**Comment by m1ga** [comment]
Did you ask for camera permissions before showing the scanner?

**Comment by inaffect-ag** [comment]
obviously - not. i feel humiliated... :)
thanks a lot, it's working!
